# This is a basic workflow to help you get started with Actions

name: Create Package Version

on: 
  workflow_dispatch:
    inputs:
      runApexTest:
        description: 'Run Apex Code Coverage'     
        required: true
        default: 'false'
      skipValidation:
        description: 'Skip Package Validation'     
        required: true
        default: 'false'   
      packageName:
        description: 'Package Name'     
        required: true
        default: 'BuyHandset'
      sourceFolder:
        description: 'Source Folder Name'     
        required: true
        default: 'force-app'  
      waitTime:
        description: 'Wait time to create Package'     
        required: true
        default: 1000    

jobs:
  createVersion:
    runs-on: ubuntu-latest
    container:
      image: jfgarcia268/sfdx_vlocity_java:latest
    steps:  
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Create Package Version 
      env:
        RUN_APEX_TESTS: ${{ github.event.inputs.runApexTest }}
        SKIP_VALIDATION: ${{ github.event.inputs.skipValidation }}  
        PACKAGE_NAME: ${{ github.event.inputs.packageName }}  
        SOURCE_FOLDER: ${{ github.event.inputs.sourceFolder }}
        WAIT: ${{ github.event.inputs.waitTime }}  
      run: |
        echo ${{ secrets.SFDX_URL_DEVHUB }}  > env.sfdx
        sfdx force:auth:sfdxurl:store -d -a ALIAS -f env.sfdx
        COMMAND="sfdx force:package:version:create -p ${PACKAGE_NAME} -d ${SOURCE_FOLDER} -k ${{ secrets.KEY }} --wait ${WAIT} -v ALIAS"      
        if ${RUN_APEX_TESTS}; then
          echo "Adding Code Coverage" 
          COMMAND="${COMMAND} --codecoverage " 
        fi
        if ${SKIP_VALIDATION}; then
          echo "Adding Skip Validation" 
          COMMAND="${COMMAND} --skipvalidation " 
        fi
        # Run sfdx force:package:version:create 
        echo "COMMAND:${COMMAND}"
        ${COMMAND}
